### ISSUE TITLE
Device serial number is truncated in the UI

### ISSUE THREAD

**Issue by cristianst85** [speed47/qpxtool#27]
Hello.

I have a LITEON iHAS124 F drive. I just noticed that this drive has a very long serial number (not sure if this is a thing with LITEON devices).

The QPxTool (v0.8.1-pl2) truncates the serial number in the UI.
![image](https://github.com/speed47/qpxtool/assets/12585988/bb2366eb-45f0-4740-a1b2-e2cc46fb98e9)

SMART-BURN Media Check v3.5.5 shows the full serial number.
![image](https://github.com/speed47/qpxtool/assets/12585988/91b94f28-c5a3-488e-91f8-0d6d9416c5e0)

ImgBurn v2.5.8.0 also shows the full serial number.
![image](https://github.com/speed47/qpxtool/assets/12585988/080787a6-80a8-4582-ad82-256087bbbc49)

P.S. I know this is an unofficial version, but I figured that I will report the issue here and (maybe) just send a link (pointing to this issue) to the QPxTool team.

**Comment by speed47** [comment]
I happen to have an iHAS324 which has a similarly long serial number. The original code truncated it at 16 chars, I've upped it to 32, which should be enough for all models and brands.
