### ISSUE TITLE
No longer starts on Win98

### ISSUE THREAD

**Issue by nscaife** [speed47/qpxtool#32]
The previous 0.7 release of qpxtool runs on Win98. It looks like the 32-bit binary is compiled for XP+ and fails to start on 98 due to missing AddVectorExceptionHandler support on this platform. I'm not sure if this is intentional, but if so it might be worth a note in the readme.

**Comment by speed47** [comment]
Good idea, I've added this information on the assets download page.

Thanks for the heads up!
